name: demo pipeline

on:
  push:
    branch: master

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello Everyone! My first cicd pipeline"
      - run: terraform version
      - run: python3 -V
      - run: aws --version